version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: expense_manager_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:${PG_PORT}'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense_manager_backend
    ports:
     - "${NEST_PORT}:${NEST_PORT}" 
    environment:
      - PORT=${NEST_PORT}
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./backend:/app/src

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: expense_manager_frontend
    ports:
      - '${NEXT_PORT}:${NEXT_PORT}'
    environment:
      - NEST_HOST=${NEST_HOST}
    volumes:
      - ./frontend:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: expense_manager_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata: